### ISSUE TITLE
irceline package on pypi

### ISSUE THREAD

**Issue by danielsjf** [dr-1/airqdata#1]
@dr-1, the irceline data parser that you wrote is great. There is also a package on pypi, but this one is much better. I was wondering if you are willing to publish it separately on pypi. If you don't have time soon, I was wondering if I could use your code, modify it a bit and publish it myself. Obviously I would reference to this project.

Concretely, I want to integrate it in [Home Assistant](https://www.home-assistant.io/). This project requires that the parser has to be published on pypi.

Let me know what you think.

**Comment by dr-1** [comment]
@danielsjf Thanks for the feedback. Good to hear you find it useful and I'm happy to publish the toolkit on PyPI shortly, though I'd prefer to keep it together as one package, with irceline.py as a submodule. That way it stays extensible to sensors from other organizations and especially users' own sensors.

In any case, with the GPL you are of course free to modify and redistribute the code for any purpose, but I appreciate that you checked first.

Suggestions and pull requests to the project are also welcome.

**Comment by dr-1** [comment]
The package is now on PyPI. Install with `pip install airqdata`.
